### ISSUE TITLE
what should i do  to get 1.docx  and 2.docx  into 3.docx

### ISSUE THREAD

**Issue by tianshangyuan** [bsonnino/WordDelphi#1]
my problem is that
How to merge two files(1.docx and 2.docx) into one(3.docx)?

**Comment by bsonnino** [comment]
This can be relatively simple or very difficult depending on what you want:
- If you want just to merge the text, open the two documents, get the text and merge them and save the same document with the merged text
- If you have fonts and images and other content, you need to merge the extra files and the relations and not only the text. This can be somewhat difficult, depending on the docs

Bruno

**Comment by tianshangyuan** [comment]
My problem  is the latter

**Comment by tianshangyuan** [comment]
have fonts and images and  mathematical formula

**Comment by bsonnino** [comment]
Then in this case, you have something very complicated and to use this technique you must study the OpenXml format and do a lot of work to merge the documents.
You can use the AltChunk (https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.altchunk?view=openxml-2.8.1) to merge the second document as an external content
One other option is to use Office Automation (you need to have Word installed) to do that. Just open the two documents, append the second and save the result, but this method doesn't use the same technique

**Comment by tianshangyuan** [comment]
You’re one in a million

**Comment by tianshangyuan** [comment]
if there is a easy way  to   merge  them(two docx) together,
it will be heavy  absorbing

**Comment by bsonnino** [comment]
The easiest way is to use Office Automation. 
Using AltChunk (see the example in C#) is the other way to do it. 

Bruno
